# Generated by Django 3.2.6 on 2022-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_number', models.IntegerField()),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Address', models.CharField(max_length=20, null=True)),
                ('tel_Number', models.CharField(max_length=20, null=True)),
                ('room_number', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(max_length=20, null=True)),
                ('time', models.TimeField(max_length=20, null=True)),
            ],
        ),
    ]
