# Generated by Django 3.2.6 on 2022-03-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_resbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resbook',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
