# Generated by Django 3.2.9 on 2022-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_resbook_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20, null=True)),
                ('no_guest', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
